version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  name: my-website-artifact
  discard-paths: yes

cache:
  paths:
    - node_modules/
